/mob/living/carbon/human/proc/climax_message_giver(type = "surface", force = 1, atom/target)
	if(gender == MALE)
		if(ishuman(target))
			switch(type)
				if("surface")
					return SPAN_ERPBOLD("You [pick("cum", "orgasm", "ejaculate")] on [target]'s body.")
				if("oral")
					return SPAN_ERPBOLD("You [pick("cum", "orgasm", "ejaculate")] inside [target]'s warm [pick("mouth", "throat")].")
				if("anal")
					return SPAN_ERPBOLD("You [pick("cum", "orgasm", "ejaculate")] inside [target]'s ass.")
				if("vaginal")
					return SPAN_ERPBOLD("You [pick("cum", "orgasm", "ejaculate")] inside [target]'s warm and wet pussy.")
				if("clothing")
					return SPAN_ERPBOLD("You [pick("cum", "orgasm", "ejaculate")] on [target]'s clothing.")
		if(isturf(target))
			return SPAN_ERPBOLD("You [pick("cum", "orgasm", "ejaculate")] on \the [target].")
		if(istype(target, /obj/item/clothing))
			return SPAN_ERPBOLD("You [pick("cum", "orgasm", "ejaculate")] in your [target].")
	else
		if(ishuman(target))
			switch(type)
				if("surface")
					return SPAN_ERPBOLD("You [pick("cum", "orgasm")] atop [target]'s body.")
				if("oral")
					return SPAN_ERPBOLD("You [pick("cum", "orgasm")] on [target]'s [pick("mouth", "lips", "face")].")
				if("anal")
					return SPAN_ERPBOLD("You twitch and shudder as you [pick("cum", "orgasm")] from intense stimulation of your ass.")
				if("vaginal")
					return SPAN_ERPBOLD("Shivers trail along your body as your pelvic muscles spasm and contract in a powerful orgasm, spewing out some of the fluid from your insides.")
				if("clothing")
					return SPAN_ERPBOLD("You [pick("cum", "orgasm")] atop [target]'s clothing.")
		if(isturf(target))
			return SPAN_ERPBOLD("You feel tiny peckles of fluid dripping down your thighs as you experience an intense flooding of sensations all over your body.")
		if(istype(target, /obj/item/clothing))
			return SPAN_ERPBOLD("You [pick("cum", "orgasm")] in your [target].")
	return

/mob/living/carbon/human/proc/climax_message_receiver(type = "surface", force = 1, target)
	switch(type)
		if("surface")
			return SPAN_ERPBOLD("You feel sticky fluid impacting and trickling down your body.")
		if("oral")
			switch(force)
				if(1)
					return SPAN_ERPBOLD("Warm salty fluid ends up in your throat.")
				if(2)
					return SPAN_ERPBOLD("Warm slimy fluid drips into your mouth.")
				if(3)
					return SPAN_ERPBOLD("Thick slime fills your mouth..")
				if(4)
					return SPAN_ERPBOLD("Thick slime trickles onto your tongue...")
	return