/decl/material/liquid/diesel
	name = "diesel"
	uid = "liquid_diesel"
	solid_name = "diesel gel"
	lore_text = "A very easy to obtain hydrocarbon."
	color = "#fda246"
	gas_tile_overlay = "generic"
	gas_overlay_limit = 0.5
	gas_specific_heat = 30
	molar_mass = 0.012
	boiling_point = 163 CELSIUS
	melting_point = -8.1 CELSIUS
	latent_heat = 2258
	gas_condensation_point = 149 CELSIUS
	gas_symbol_html = "C<sub>12<sub>H<sub>23<sub>"
	gas_symbol = "C12H23"
	scannable = 1
	metabolism = REM
	taste_description = "disgusting oil and freedom"
	glass_name = "gold elixir"
	slipperiness = 8
	dirtiness = DIRTINESS_NEUTRAL
	turf_touch_threshold = 0.1
	liquid_density = 875
	combustion_chamber_fuel_value = 240 MJ
	fuel_value = 2
	gas_flags = XGM_GAS_FUEL
	burn_product = /decl/material/gas/carbon_monoxide