/decl/material/liquid/diesel
	name = "diesel"
	uid = "diesel"
	solid_name = "diesel gel"
	lore_text = "A very easy to obtain hydrocarbon."
	color = "#fda246"
	gas_tile_overlay = "generic"
	gas_overlay_limit = 7
	gas_specific_heat = 30
	molar_mass = 0.012
	boiling_point = 163 CELSIUS
	melting_point = -8.1 CELSIUS
	latent_heat = 5000
	gas_condensation_point = 149 CELSIUS
	gas_symbol_html = "C<sub>12<sub>H<sub>23<sub>"
	gas_symbol = "C12H23"
	scannable = 1
	metabolism = REM
	taste_description = "disgusting oil and freedom"
	glass_name = "gold elixir"
	slipperiness = 8
	dirtiness = DIRTINESS_NEUTRAL
	turf_touch_threshold = 0.1
	liquid_density = 875
	combustion_chamber_fuel_value = 8.4 MJ
	fuel_value = 2
	gas_flags = XGM_GAS_FUEL
	combustion_energy = 537600
	combustion_activation_energy = 48500
	oxidizer_to_fuel_ratio = 12.5
	combustion_products = list(/decl/material/gas/oxygen = /decl/material/gas/carbon_dioxide)
	burn_product = /decl/material/gas/carbon_monoxide

/decl/material/liquid/biodiesel
	name = "biodiesel"
	uid = "biodiesel"
	solid_name = "biodiesel gel"
	lore_text = "Biodiesel is a renewable, biodegradable fuel manufactured domestically from vegetable oils, animal fats, or recycled restaurant grease."
	color = "#ffbb77"
	gas_tile_overlay = "generic"
	gas_overlay_limit = 7
	gas_specific_heat = 2.5
	molar_mass = 0.012
	boiling_point = 325 CELSIUS
	melting_point = -35 CELSIUS
	latent_heat = 5000
	gas_condensation_point = 315 CELSIUS
	gas_symbol_html = "C<sub>17<sub>H<sub>36<sub>"
	gas_symbol = "C17H36"
	scannable = 1
	metabolism = REM
	taste_description = "plant activism"
	glass_name = "gold nectar"
	slipperiness = 6
	dirtiness = DIRTINESS_NEUTRAL
	turf_touch_threshold = 0.1
	liquid_density = 885
	combustion_chamber_fuel_value = 6.3 MJ
	fuel_value = 1.8
	gas_flags = XGM_GAS_FUEL
	combustion_energy = 517600
	combustion_activation_energy = 58600
	oxidizer_to_fuel_ratio = 3
	combustion_products = list(/decl/material/gas/oxygen = /decl/material/gas/carbon_dioxide)
	burn_product = /decl/material/gas/carbon_dioxide