/mob/living/carbon/human/proc/debug_medicine(user)
	var/obj/item/organ/internal/heart/H = GET_INTERNAL_ORGAN(src, BP_HEART)
	to_chat(user, "Heart Rate: [round(bpm)]")
	to_chat(user, "Heart Instability: [H.instability]")
	to_chat(user, "Heart CO: [H.cardiac_output * 100]%")
	to_chat(user, "MCV: [mcv] ([round(bpm)] * [round(get_stroke_volume())])")
	to_chat(user, "TPVR: [tpvr]")
	to_chat(user, "Blood Pressure: ([syspressure]/[dyspressure])")
	to_chat(user, "Blood Saturation: [get_blood_saturation() * 100]%")
	to_chat(user, "Blood Perfusion: [get_blood_perfusion() * 100]%")
	to_chat(user, "Blood Volume: [get_blood_volume_hemo() * 100]%")
	return
